apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: assignment-portal
spec:
  storageClassName: gp3-storage

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi
