apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: assignment-portal

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: ecr-registry-secret

      containers:
        - name: backend
          image: 003344631245.dkr.ecr.us-east-1.amazonaws.com/assignment-portal-backend:77fd0abddeb0d3fefcf1765151246247bc28117e
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: assignment-portal-config
                  key: FLASK_ENV

            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: assignment-portal-config
                  key: REDIS_URL

            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/assignment_portal_db"

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: assignment-portal-secret
                  key: SECRET_KEY

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
